# Generated by Django 3.2.4 on 2022-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='leads'),
        ),
    ]
